# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7630ce14bb046761ccd8574dd3729a47080e09dd89938f80914fe217022e98ef6bd8fb83f07635c1a27a2683c6f43d08c8f0c7d9abdbaced08669af2803def64

test:
  secret_key_base: 08cde0175140c9157cd050f7a3e714e29b27390f7adfa3ba7cdee66009ebd47eca9e14bef3061e2e2981c029fea8c7a7b4f2c064a9c26013da1df0c0145ec879

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
